auth: # TODO
  default_driver: jwt
  drivers:
    jwt:
      enabled: true
      algorithm: HS256
      secret: demopass
      refresh_ttl: 1209600  # 2 weeks, in seconds
      ttl: 7200             # 2 hours, in seconds
#    oauth2:
#      enabled: false
#      clientId: demoapp
#      clientSecret: demopass
#      redirectUri: http://localhost
#      urlAuthorize: http://brentertainment.com/oauth2/lockdin/authorize
#      urlAccessToken: http://brentertainment.com/oauth2/lockdin/token
#      urlResourceOwnerDetails: http://brentertainment.com/oauth2/lockdin/resource
