doctrine:
  dbal:
    default_connection: default
    types: ~
    schema_filter: ~
    connections:
      default:
        dbname: ~
        host: 127.0.0.1
        port: ~
        user: root
        password: ~
        charset: utf8
        unix_socket: ~
        driver: pdo_mysql
        auto_commit: false
        logging: ~
        mapping_types: ~
  orm:
    default_entity_manager: default
    auto_generate_proxy_classes: 0
    proxy_dir: /path/to/proxy/dir
    proxy_namespace: DoctrineProxies
    entity_managers:
      default:
        query_cache_driver:
          type: array
        metadata_cache_driver:
          type: array
        result_cache_driver:
          type: array
        connection: default
        class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
        default_repository_class: Doctrine\ORM\EntityRepository
        repository_factory: ~
        mappings:
          default:
            mapping: true
            type: annotation
            dir: /path/to/entity/dir
        ast: ~
        dql:
          string_functions: ~
          numeric_functions: ~
          datetime_functions: ~
